name: CloneRepo
on: [push]
jobs:
 runs-on: ubuntu-latest
 steps:
    - name: Check out my other private repo
         uses: actions/checkout@master
          with:
          repository: rodalu/apiops
          token: ${{ secrets.my_pat }}
