name: CloneRepo
on: [push]
jobs:
 runs-on: ubuntu-latest
 steps:
 - name: rodalu/apiops PUBLIC repository
  uses: rodalu/apiops-action@v2.3
  with:
    depth: 1
    branch: 'main'
    owner: 'rodalu'
    repository: 'apiops'
