name: CloneRepo

on: 
  workflow_dispatch:
  push:

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
    - name: Clone apiops repository
      uses: actions/checkout@v2
      with:
        repository: rodalu/apiops2
        path: rodalu/apiops
        ref: 2.x
        image: $(params.gitInitImage)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         with:
            logLevel: debug