name: CloneRepo

on: 
  workflow_dispatch:
  push:

jobs:  
     job-public-repo-windows:
      runs-on: windows-latest
      steps:

        - name: rodalu/apiops PUBLIC repository
          uses: rodalu/clone-apiops@main
          with:
              owner: 'rodalu'
              repository: 'apiops'
      
        - name: Access cloned repository content
          run: |
            echo "ROOT"
            ls -la
            echo "CLONED REPO"
            cd apiops
            ls -la
            shell: bash