name: CloneRepo

on: 
  workflow_dispatch:
  push:

jobs:  
     job-public-repo-windows:
      runs-on: windows-latest
      steps:

        - name: rodalu/DemoClone PUBLIC repository
          uses: rodalu/DemoClone@main
          with:
              owner: 'rodalu'
              repository: 'DemoClone'
      
        - name: Access cloned repository content
          run: |
            echo "ROOT"
            ls -la
            echo "CLONED REPO"
            cd DemoClone
            ls -la
            shell: bash
            logLevel: debug