name: my workflow
on:
    workflow_dispatch:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT

    - name: Set env QA
      run: echo "QA_ENVI=$(echo $QA_ENVI| cut -c 1-6)" >> $GITHUB_ENV
      env: 
         QA_ENVIRONMENT: QA_Environment

    - name: Test QA ENVIRONMENT
      run: echo $QA_ENVI