name: DEV

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  check_api:
    runs-on: ubuntu-latest
    steps:
        - shell: pwsh
          env:
            SUPER_SECRET: ${{ secrets.PERSONAL_TOKEN }}
          run: |
            example-command "$env:SUPER_SECRET"

