name: Copy To Branches
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Checkout
       run: |
           git checkout main
     - name: GitHub Create Branch
       run: |
            git branch testbranch        
