name: DEV

on:

  push:
  workflow_dispatch:
     
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git checkout -b "Feature/api-code-change
