name: Copy To Branches
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1
    - name: Create Branch
      run: |
          echo '$ git branch testbranch'
        
