name: DEV

on:

  push:
  workflow_dispatch:
     
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git new branch
      run: |
           git checkout -b "Feature/api-code-changes
