name: Copy To Branches
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Checkout
       run: |
          echo $ git checkout testbranch
     - name: GitHub Create Branch
       run: |
           echo $ git branch testbranch        
