name: Copy To Branches
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Create Branch
       run: |
           echo git branch feature/api-code-changes
          
