name: GraphAPI

on:
   workflow_dispatch:
   push: 
     branches: [ main ]
jobs:
    operations:
      runs-on: ubuntu-latest
      steps:
      - name: Check File  
        uses: actions/checkout@v1

      - name: DEMOCLONE
        uses: rodalu/DEMOCLONE@main
        
        with:
          schema_location: ${{ github.workspace }}/schema/schema.graphql
          base_dir: ${{ github.workspace }}/schema
          excluded_paths: schema.graphql
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'main:schema/local/schema.graphql'
          annotations: true