name: TestGQL

on:
   workflow_dispatch:
   push: 
   
jobs:
    operations:
      runs-on: ubuntu-latest
      steps:
      - name: Check File  
        uses: actions/checkout@v1

      - name: Graph QL Schema
        uses: rodalu/DEMOCLONE@main        

        with:       
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'main:schema/schema.graphql'
          annotations: true