name: TestGQL

on:
   workflow_dispatch:
   push: 
   
jobs:
    operations:
      runs-on: ubuntu-latest
      steps:
      - name: Check File  
        uses: actions/checkout@v1

      - name: Graph QL Schema
        uses: rodalu/DEMOCLONE@main        

        with:       
          github-token: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_BASE: ${{ github.base_ref }}
          INPUT_HEAD: ${{ github.ref }}
          schema: 'main:schema/schema.graphql'
          query: sample/repository-static.query.yaml
          annotations: true