
name: GraphQLAPI

on:
  workflow_dispatch:
  push: 
     branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
      with: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        schema: 'main: schema/local/schema.graphql' 
        annotation: true
          
   
    - name: Run a one-line script and path
      run: echo Testing one liner    
    

   
    # - name: Install graphQL
    - name: Query Schema
      run: |
         npm install graphql-http
          -- push\
          -- graph=Stream-Helpers\     
          -- key=${{ secrets.GITHUB_TOKEN}}\      
          -- variant=current \
          -- content-filepath: ./schema/schema.grapql
          -- localSchemaFile=./schema/schema.graphql
          #  echo "$HOME/.local/bin" >> $GITHUB_PATH
          #  echo $ /usr/bin/env bash
             query: localSchemaFile=./schema/schema.graphql

         

    - name: Query Schema
      run : |
           query {
              PersonalInfo
                }