
name: GraphQLAPI

on:
  workflow_dispatch:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Testing one liner

   
    - name: Install graphQL
      run: |
        npm install graphql-http
          -- push\
          -- graph=Stream-Helpers\     
          -- key=${{ secrets.GITHUB_TOKEN}}\
          -- variant=current \
          -- localSchemaFile=./schema/schema.graphql