
name: GraphQLAPI

on:
  workflow_dispatch:
  push: 
     branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
  
          
   
    - name: Github OctoCat
      run: echo Testing one liner    
           curl --request GET \
        -- url "https://api.github.com/octocat" \

        
    - name: Current Price Json
      run: echo Testing one liner    
             curl --request GET \
        -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \
   
    # # - name: Install graphQL
    # - name: Install Graph QL
    #   run: |
    #      npm install graphql-http
    #      curl -i --header "${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
    #      echo "/HolismHolding/Commands" >> $GITHUB_PATH
    #       -- push\
    #       -- graph=Stream-Helpers\     
    #       -- key=${{ secrets.GITHUB_TOKEN }}\      
    #       -- variant=current \
    #       #-- content-filepath: ./schema/schema.grapql
    #       #-- localSchemaFile=./schema/schema.graphql
    #       #  echo "$HOME/.local/bin" >> $GITHUB_PATH
    #       #  echo $ /usr/bin/env bash

    # - name: GraphQuery
    #   run: |   
    #     -- push\
    #     -- graph=Stream-Helpers\     
    #     -- key=${{ secrets.GITHUB_TOKEN }}\      
    #     -- variant=current \
    #     #-- content-filepath: ./schema/schema.grapql
    #     #-- localSchemaFile=./schema/schema.graphql
    #     #  echo "$HOME/.local/bin" >> $GITHUB_PATH
    #     #  echo $ /usr/bin/env bash
    #         query {
    #           __schema {
    #             types {
    #               name
    #               kind
    #               description
    #               fields {
    #                 name
    #               }
    #             }
    #           }
    #         }

    - name: Test URL
      run : |
          curl --request POST \
          -- url "https://datausa.io/api/data?drilldowns=Nation&measures=Population" \
          -- user "YOUR_CLIENT_ID:secrets.GITHUB_TOKEN" \
          -- header "Accept: application/vnd.github+json" \
          -- header "X-GitHub-Api-Version: 2022-11-28" \
          -- data '{
            "access_token": "ACCESS_TOKEN_TO_CHECK"
           }'