name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Query Schema
          run: |
             npm install graphql-http
              -- push\
              -- graph=Stream-Helpers\     
              -- key=${{ secrets.GITHUB_TOKEN}}\      
              -- variant=current \
              -- content-filepath: ./schema/schema.grapql
              -- localSchemaFile=./schema/schema.graphql
  