name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \

        
         - name: Current Price Json
           run: echo Testing one liner    
             curl --request GET \
             -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \  


         - name: Test URL using JSON file
           run : |
             curl --request POST \
              -- url "https://api.ipify.org?format=json" \
             # -- header "Accept: application/vnd.github+json" \
       
         - name: Test URL using JSON file
           run : |
            curl -H "Authorization: bearer TOKEN" -X POST -d " \
             { \
              \"query\": \"query { viewer { login }}\" \
             } \
            " https://api.coindesk.com/v1/bpi/currentprice.json


         - name: Test URL using JSON file0
           run : |
              curl -H "Authorization: bearer TOKEN" -X POST -d " \
              { \
              \"query\": \"query { viewer { login }}\" \
              } \
              " https://api.coindesk.com/v1/bpi/currentprice.json
              # knit: (function(inputFile, encoding) { 
              #   rmarkdown::render(inputFile,
              #                 encoding=encoding, 
              #                 output_file='new_file_name.html')) })