name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
        args-query:
          runs-on: ubuntu-16.04
          steps:
          - uses: actions/checkout@v2
          - uses: ./
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              query: schema/schema.grapql
              owner: rodalu
              name: github-graphql-action