name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \
              
        
         - name: Current Price Json BPI
           run: |   
             curl --request GET \
             -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \  
             -- header "Accept: application/vnd.github+json" \

         - name: Current Repo review
           run: |   
             curl -L \
             - H "Accept: application/vnd.github+json" \
             - H "Authorization: Bearer <YOUR-TOKEN>" \
             - H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/rodalu/REPO/workflows/package.json
   
   