name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  check_api:
    runs-on: ubuntu-latest
    steps:     
         - uses: actions/checkout@v2
         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \

         - name: Current Price Json BPI
           run: |   
                   curl -L \
                   -H "Accept: application/vnd.github+json" \
                   -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   https://api.coindesk.com/v1/bpi/currentprice.json  -o "outputfile1.txt"           
   
  check_graphql:
    runs-on: ubuntu-latest
    steps:  
         - uses: actions/checkout@v2  
         
        #  - name: Load files
        #    uses: ./
        #    id: repositoryyaml
        #    with:
        #       path: https://api.github.com/repos/democlone/sample/repository-static.query.yaml

         - name: graphql read files
           run: |
            curl --request GET \
            --url "https://api.github.com/repos/democlone" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer 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"


  test_graphql:
    runs-on: ubuntu-latest
    steps:  
         - uses: actions/checkout@v2  
         - name: Current Query Users Json
           run: |           
                curl -H "Authorization: bearer TOKEN" -X POST -d " \
                { \
                  \"query\": \"query { viewer { login }}\" \
                  } \
                " https://api.coindesk.com/v1/bpi/currentprice.json  

         - name: Graphql Mutations
           run: |  
                curl 'https://jsonplaceholder.typicode.com/users' \
                -X POST \
                -H 'Authorization: Token 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' \
                -H 'content-type: application/json' \
                --data '{
                  "query": "{ users { email } }"
                }'       
                
         - name: Print GraphQL Mutation 
           run: |   
              curl 'https://jsonplaceholder.typicode.com/users' \
              -X POST \
              -D - \
              -H 'content-type: application/json' \
              --data '{
                "query": "{ users { username mail } }"
              }'  

         - name: Print GraphQL Mutation 
           run: |   
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"query":"query { medication ( where:{ _and: [ { diagnosis_code: {_in: [\"S00-T88\",\"T20-R73\"]}}, 
            { price: {_lt: 150}}, { inventory: {_gt: 10}} ] } ) { id name diagnosis_code price inventory } }","variables":null}' \
            https://hasura-graphql-test.herokuapp.com/v1alpha1/graphql
                
   