name: GraphQL_ENDPOINT

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2
     
         - name: Test Query Users
           run: |   
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"query":"query { users ( where:{ _and: [ { diagnosis_code: {_in: [\"S00-T88\",\"T20-R73\"]}}, 
            { price: {_lt: 150}}, { users: {_gt: 10}} ] } ) { email, id } }","variables":null}' \
            https://jsonplaceholder.typicode.com/users
        
         - name: Test Query JSON File from REPO
           run: |   
              curl -H "Authorization: 'bearer' + PERSONAL_TOKEN " -X POST -d " \
              { \
                \"query\": \"query { viewer { login }}\" \
              } \
              " https://api.github.com/graphql

              
  graphqltestquery:
    runs-on: ubuntu-latest
    steps:  
         - uses: actions/checkout@v2  
         - name: Test Sample
           run: |           
            curl -X POST -H "Authorization: 'bearer ' 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" \
            -H "Content-Type: application/json" \
            -d '{"query": "query { repository(owner:\"octocat\", name:\"hello-world\") { name description primaryLanguage { name } } }"} '\
             https://api.github.com/graphql