name: GraphQL_ENDPOINT

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  api_graphqlquery:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2
     
         - name: Test Query Users
           run: |   
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"query":"query { users ( where:{ _and: [ { diagnosis_code: {_in: [\"S00-T88\",\"T20-R73\"]}}, 
            { price: {_lt: 150}}, { users: {_gt: 10}} ] } ) { email, id } }","variables":null}' \
            https://jsonplaceholder.typicode.com/users
        
         - name: Test Repo graphql Query
           run: |   
              curl -H "Authorization: ${{secrets.PERSONAL_TOKEN}}" -X POST -d " \
              { \
                \"query\": \"query { viewer { login }}\" \
              } \
              " https://api.github.com/graphql

              
  graphqltestquery:
    runs-on: ubuntu-latest
    steps:  
         - uses: actions/checkout@v2  
         - name: Repo GraphQL
           run: |           
            curl -X POST -H "Authorization: ${{secrets.PERSONAL_TOKEN}}" \
            -H "Content-Type: application/json" \
            -d '{"query": "query { repository(owner:\"rodalu\", name:\"hello-world\") { name description primaryLanguage { name } } }"} '\
             https://api.github.com/graphql