name: GraphQL 
on: 
  workflow_dispatch:
  push:

jobs: ## jobs to run when triggered
  build:
    runs-on: ubuntu-latest ## which machine the job runs on
    steps: ## steps to run
      - name: Step One ## name of a step
        run: | ## commands to run 
            echo '${{ github.event.ref }}'
