name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \
              
        
         - name: Current Price Json
           run: |   
             curl --request GET \
             -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \  
             -- header "Accept: application/vnd.github+json" \


         - name: Test URL using JSON file
           run : |
             curl --request POST \
              -- url "https://api.ipify.org?format=json" \
              -- header "Accept: application/vnd.github+json" \
                   
         - name: Test URL wit header
           run : |
             curl --request POST \
              -- url "https://api.coindesk.com/v1/bpi/currentprice.json?format=json" \
              -- header "Accept: application/vnd.github+json" \
          
   
   