name: GraphQuery

on: 
    workflow_dispatch:
    push:

jobs: ## jobs to run when triggered
        echo-branch-name: ## name of a job
          runs-on: ubuntu-latest ## which machine the job runs on
          steps: ## steps to run
            - name: Step One ## name of a step
              run: | ## commands to run 
                #   echo '${{ github.event.ref }}'
                {
                users(usernames: ["user1", "user3", "user4"]) {
                    pageInfo {
                    endCursor
                    startCursor
                    hasNextPage
                    }
                    nodes {
                    id
                    username,
                    publicEmail
                    location
                    webUrl
                    userPermissions {
                        createSnippet
                    }
                    }
                }
                }