name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
        static-query:
          runs-on: ubuntu-16.04

          - name: Query Schema
            run: |
            npm install graphql-http
          steps:
          - uses: actions/checkout@main
          - uses: ./.github/actions/sample
          - uses: actions/checkout@v2
          - uses: ./


              -- push\
               env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 with:
              query: sample/repository-static.query.yml

          
  