name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \
              
        
         - name: Current Price Json
           run: echo Testing one liner    
             curl --request GET \
             -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \  


         - name: Test URL using JSON file
           run : |
             curl --request POST \
              -- url "https://api.ipify.org?format=json" \
              -- header "Accept: application/vnd.github+json" \
       
         - name: Test URL with quesry JSON file
           run : |
                 curl -H "Authorization: bearer TOKEN" -X POST -d " \
                 { \
                  \"query\": \"query { viewer { login }}\" \
                  } \
                   " https://api.coindesk.com/v1/bpi/currentprice.json \
        

         - name: Github Users
           run: echo Testing one liner    
               https://api.github.com/authorizations 
      
         - name: Github Users Read File
           run: |   
                curl -X POST -H "Content-Type: application/json" -d @../configurations/test.json https://api.github.com/users
               
         - name: Test Package.json
           run: |
                  echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
                  cat ./package.json >> $GITHUB_ENV
                  echo 'EOF' >> $GITHUB_ENV
          #  run: |
          #         echo '${{ fromJson(env.PACKAGE_JSON).version }}'

         - name: Github Test Query
           run: |   
                https://api.github.com/authorizations 
                  type Query {
                   users: [User]
                    }

                    type User {
                    id: String!
                        name: String!
                        }