name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  check_api:
    runs-on: ubuntu-latest
    steps:     
         - uses: actions/checkout@v2
         - name: Github OctoCat
           run: echo Testing one liner    
              curl --request GET \
              -- url "https://api.github.com/octocat" \
              
         
         - name: Current Price Json BPI
           run: |   
             curl --request GET \
             -- url "https://api.coindesk.com/v1/bpi/currentprice.json" \  
             -- header "Accept: application/vnd.github+json" \

         - name: Load files
           uses: ./
           id: yamlfile
           with:
              path: api.github.com/repos/sample/repository-static.query.yaml
    
  check_graphql:
    runs-on: ubuntu-latest
    steps:  
         - uses: actions/checkout@v2        
         - name: graphql read files
           run: |
            curl --request GET \
            --url "https://api.github.com/repos/democlone" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer $GIT_TOKEN"

         

   
   