name: GraphQuery

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Query Schema
          run: |
             npm install graphql-http
              -- push\
              -- graph=Stream-Helpers\     
              -- key=${{ secrets.GITHUB_TOKEN}}\      
              -- variant=current \
              -- content-filepath: ./schema/schema.grapql
              -- localSchemaFile=./schema/schema.graphql
  



              # # - name: Install graphQL
              # - name: Install Graph QL
              #   run: |
              #      npm install graphql-http
              #      curl -i --header "${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
              #      echo "/HolismHolding/Commands" >> $GITHUB_PATH
              #       -- push\
              #       -- graph=Stream-Helpers\     
              #       -- key=${{ secrets.GITHUB_TOKEN }}\      
              #       -- variant=current \
              #       #-- content-filepath: ./schema/schema.grapql
              #       #-- localSchemaFile=./schema/schema.graphql
              #       #  echo "$HOME/.local/bin" >> $GITHUB_PATH
              #       #  echo $ /usr/bin/env bash
          
              # - name: GraphQuery
              #   run: |   
              #     -- push\
              #     -- graph=Stream-Helpers\     
              #     -- key=${{ secrets.GITHUB_TOKEN }}\      
              #     -- variant=current \
              #     #-- content-filepath: ./schema/schema.grapql
              #     #-- localSchemaFile=./schema/schema.graphql
              #     #  echo "$HOME/.local/bin" >> $GITHUB_PATH
              #     #  echo $ /usr/bin/env bash
              #         query {
              #           __schema {
              #             types {
              #               name
              #               kind
              #               description
              #               fields {
              #                 name
              #               }
              #             }
              #           }
              #         }
          
              # - name: Test URL with Post 
              #   run : |
              #      curl --request POST \
              #      -- url "https://datausa.io/api/data?drilldowns=Nation&measures=Population" \
          
              #      -- header "Accept: application/vnd.github+json" \
              #      -- data '{
              #              "access_token": "ACCESS_TOKEN_TO_CHECK"
              #             }'