name: GraphAPI

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github ReadFile
           run:  source ${GITHUB_ACTION_PATH}/sample/repository-static.query.yaml
  