name: GraphAPI

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Current Price Json BPI
          run:  $GITHUB_ACTION_PATH/package.json
          shell: bash