name: GraphAPI

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github ReadFile  
           run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rodalu/REPO/actions/workflows/action.yml   


         - name: Current Price Json BPI
           run: |   
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.coindesk.com/v1/bpi/currentprice.json

         - name: Current Graphql
           run: |   
                curl \
                -X POST \
                -H "x-api-key: xxx-xxxx" \
                -H "Content-Type: application/json" \
                -d '{ "query": "mutation($user: UserInput!) { createUser(user: $user) { name location id } }" ,
                        "variables": {
                        "user": {
                            "name": "Nader Dabit",
                            "location": "United States",
                            "id": "001"
                        }
                        }
                    }' \
                https://app-id.appsync-api.us-east-1.amazonaws.com/graphql

         - name: Current Access Token
           run: |
                curl --request GET \
                --url "https://api.github.com/repos/octocat/Spoon-Knife/issues" \
                --header "Accept: application/vnd.github+json" \
                --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"           

         - name: Current GraphQry
           uses: rodalu/DEMOCLONE@v1
           id: comment-branch
        
         - name: Run QUery
           run: |   
                status=$(curl -s --request POST \
                --url https://x.com/api \
                --header 'Token: ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{"parameters": {"run_workflow_test":true, "source_branch":"${{ steps.comment-branch.outputs.head_ref }}"}
                }' | jq -r '.state'); echo "status=$status" >> $GITHUB_OUTPUT
                id: req

     