name: GraphAPI

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github ReadFile  
           run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rodalu/REPO/actions/workflows/action.yml   


         - name: Current Price Json BPI
           run: |   
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.coindesk.com/v1/bpi/currentprice.json  -o "outputfile1.txt"        

         - name: Current Graphql
           run: |   
                curl \
                -X POST \
                -H "x-api-key: xxx-xxxx" \
                -H "Content-Type: application/json" \
                -d '{ "query": "mutation($user: UserInput!) { createUser(user: $user) { name location id } }" ,
                        "variables": {
                        "user": {
                            "name": "Nader Dabit",
                            "location": "United States",
                            "id": "001"
                        }
                        }
                    }' \
                https://app-id.appsync-api.us-east-1.amazonaws.com/graphql
        
         - name: Run Query using Bash and Curl
           run: |   
                echo '{ "query":
                    "{
                    viewer {
                        zones(filter: { zoneTag: $zoneTag }) {
                        firewallEventsAdaptive(
                            filter: $filter
                            limit: 10
                            orderBy: [datetime_DESC]
                        ) {
                            action
                            clientAsn
                            clientCountryName
                            clientIP
                            clientRequestPath
                            clientRequestQuery
                            datetime
                            source
                            userAgent
                        }
                        }
                    }
                    }",
                    "variables": {
                    "zoneTag": "<zone-tag>",
                    "filter": {
                        "datetime_geq": "2022-07-24T11:00:00Z",
                        "datetime_leq": "2022-07-24T12:00:00Z"
                    }
                    }
                }' | tr -d '\n' | curl \
                    -X POST \
                    -H "Content-Type: application/json" \
                    -H "X-Auth-Email: rodel.boy.aluzan@accenture.com" \
                    -H "X-Auth-key: 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" \
                    -s \
                    -d @- \
                    https://api.cloudflare.com/client/v4/graphql/

     