name: GraphAPI

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github ReadFile  
           run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rodalu/REPO/actions/workflows/action.yml   


         - name: Current Price Json BPI
           run: |   
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.coindesk.com/v1/bpi/currentprice.json

         - name: Current Graphql
           run: |   
                curl \
                -X POST \
                -H "x-api-key: xxx-xxxx" \
                -H "Content-Type: application/json" \
                -d '{ "query": "mutation($user: UserInput!) { createUser(user: $user) { name location id } }" ,
                        "variables": {
                        "user": {
                            "name": "Nader Dabit",
                            "location": "United States",
                            "id": "001"
                        }
                        }
                    }' \
                https://app-id.appsync-api.us-east-1.amazonaws.com/graphql

         - name: Current GraphQry
           run: |   
             curl -i -H 'Content-Type: application/json' -H "Authorization: bearer myGithubAccessToken" -X POST 
             -d '{"query": "query {repository(owner: \"wso2\", name: \"product-is\") {description}}"}'
              https://api.github.com/graphql


         - name: Current Bank 
           run: |   
                     curl \
                     -X POST \
                     -H "x-api-key: xxx-xxxx" \
                     -H "Content-Type: application/json" \
                     -d '{ "query": "mutation($user: UserInput!) { createUser(user: $user) { name location id } }" ,
                             "variables": {
                             "bpi": {
                                 "code": "USD"                          
                             }
                             }
                         }' \
                         https://api.coindesk.com/v1/bpi/currentprice.json