name: GraphAPI

on:
   workflow_dispatch:
   push: 
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: ./
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            query: sample/repository-static.query.yaml