name: GraphAPI

on:
   workflow_dispatch:
   push: 
      branches: [ main ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
         - uses: actions/checkout@v2

         - name: Github ReadFile  
           run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rodalu/REPO/actions/workflows/action.yml   


         - name: Current Price Json BPI
           run: |   
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: ${{ secrets.GITHUB_TOKEN }} " \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.coindesk.com/v1/bpi/currentprice.json  -o "outputfile1.txt"        

         - name: Current Graphql
           run: |   
                curl \
                -X POST \
                -H "x-api-key: xxx-xxxx" \
                -H "Content-Type: application/json" \
                -d '{ "query": "mutation($user: UserInput!) { createUser(user: $user) { name location id } }" ,
                        "variables": {
                        "user": {
                            "name": "Nader Dabit",
                            "location": "United States",
                            "id": "001"
                        }
                        }
                    }' \
                https://app-id.appsync-api.us-east-1.amazonaws.com/graphql

         - name: Current Access Token
           run: |
                curl --request GET \
                --url "https://api.github.com/repos/octocat/Spoon-Knife/issues" \
                --header "Accept: application/vnd.github+json" \
                --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o "outputfile1.txt"           

         - name: Current GraphQry
           uses: ./
           id: comment-branch
        
         - name: Run QUery
           run: |   
                curl -g \
                -X POST \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer 8c7dbd270cb98e83f9d8d57fb8a2ab7bac9d7501905fb013c69995ebf1b2a719" \
                -d '{"query":"query{showCollection {items { title firstEpisodeDate lastEpisodeDate henshinMp4 { url }}}}"}' \
                https://graphql.contentful.com/content/v1/spaces/mt0pmhki5db7

     