name: Environment_Setup

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        uses: rodalu/DEMOCLONE@v1
        with:
          ENV_TEST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          ENV_ANOTHER_KEY: ${{ secrets.GITHUB_TOKEN }}