name: Environment_Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |         
          echo "${{ secrets.GITHUB_TOKEN }}" > .env



          