name: Environment_Setup

on:
  workflow_dispatch:
  push:

jobs: 
   Environments:
    runs-on: ubuntu=latest
    env:
      Dev_Environment: Dev_Environment
    steps:
       - name: Read ENV
         run: echo "Dev Environment ${{env.Dev_Environment}}"


          